name: Build and Push Docker images
on:
  push:
    branches:
      main

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    - name: Build and push Docker image
      uses: matootie/github-docker@v3.0.0
      with:
        accessToken: ${{secrtes.fastapi}}
        tags: latest
        imageName: ${{ github.repository}}