name: sonarqube
on:
  push:
    branches:
      - main
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Install dependencies
        run: yarn install --production=false
      - name: Scan code
        uses: kitabisa/sonarqube-action@master
        with:
          host: ${{ secrets.SONAR_HOST_URL }}
          login: ${{ secrets.SONAR_TOKEN }}
          githubToken: ${{ secrets.FASTAPI }} # https://docs.github.com/en/actions/reference/authentication-in-a-workflow#about-the-github_token-secret
